# Generated by Django 6.0.5 on 2026-05-19 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('singles_elo', models.FloatField(default=1000.0)),
                ('doubles_elo', models.FloatField(default=1000.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], max_length=10)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team1_score', models.PositiveSmallIntegerField()),
                ('team2_score', models.PositiveSmallIntegerField()),
                ('team1_players', models.ManyToManyField(related_name='team1_games', to='tracker.player')),
                ('team2_players', models.ManyToManyField(related_name='team2_games', to='tracker.player')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='EloChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_before', models.FloatField()),
                ('elo_after', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_changes', to='tracker.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_changes', to='tracker.player')),
            ],
            options={
                'ordering': ['game__played_at'],
            },
        ),
    ]
