# Generated by Django 6.0.5 on 2026-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_location_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
