# Generated by Django 6.0.5 on 2026-06-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_player_remove_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name', 'last_name', 'nickname']},
        ),
    ]
