# Generated by Django 6.0.5 on 2026-06-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_openskill_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingchange',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='tracker.game'),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='mu_after',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='mu_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='tracker.player'),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='sigma_after',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratingchange',
            name='sigma_before',
            field=models.FloatField(),
        ),
    ]
